# Generated by Django 4.2.4 on 2024-01-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momos',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='chicken_momo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('Momo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momo.momos')),
            ],
        ),
        migrations.CreateModel(
            name='buff_momo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('Momo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='momo.momos')),
            ],
        ),
    ]
