# Generated by Django 4.2.4 on 2024-01-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0002_alter_momos_description_chicken_momo_buff_momo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='momo.momocategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='chicken_momo',
            name='Momo',
        ),
        migrations.DeleteModel(
            name='buff_momo',
        ),
        migrations.DeleteModel(
            name='chicken_momo',
        ),
        migrations.DeleteModel(
            name='momos',
        ),
    ]
