# Generated by Django 4.2.4 on 2024-01-24 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0003_momocategory_product_remove_chicken_momo_momo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='allmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Allmenu')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='momo.momocategory')),
            ],
        ),
    ]
