# Generated by Django 4.2.4 on 2024-01-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0004_menucategory_allmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allmenu',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='momo.menucategory'),
        ),
    ]
